services:
  # Frontend (React + Vite)
  web:
    build:
      context: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app:cached
      - web_node_modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
    depends_on:
      - api

  # Backend (NestJS API)
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app:cached
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=devfinder_user
      - DB_PASSWORD=devfinder_pass
      - DB_NAME=devfinder_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:dev
    depends_on:
      - postgres
      - redis

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devfinder_user
      - POSTGRES_PASSWORD=devfinder_pass
      - POSTGRES_DB=devfinder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # pgAdmin - веб-интерфейс для PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@devfinder.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  web_node_modules:
  api_node_modules: